import { Guitar } from '../types/guitar-type';
import { GuitarType } from '../types/guitar-type.enum';
import { StringsNumber } from '../types/strings-number.enum';

export const guitars: Guitar[] = [
  {
    title: 'Guitar1',
    description: 'Best guitar',
    photo:'',
    id:'1234fghkil',
    stringsNumber: StringsNumber.Seven,
    guitarType: GuitarType.Ukulele,
    vendorCode: '123456',
    price: 100,
    createdAt: '2023-9-15',
  },
  {
    title: 'Guitar2',
    description: 'Not good guitar',
    photo:'',
    id:'rtghyokk123',
    stringsNumber: StringsNumber.Four,
    guitarType: GuitarType.Ukulele,
    vendorCode: '123456',
    price: 150,
    createdAt: '2023-9-15',
  },
  {
    title: 'Guitar3',
    description: 'Better then before',
    photo:'',
    id:'rtghyodsvc3',
    stringsNumber: StringsNumber.Six,
    guitarType: GuitarType.Acoustic,
    vendorCode: '123456',
    price: 150,
    createdAt: '2023-9-15',
  },
  {
    title: 'Guitar4',
    description: 'Not good guitar',
    photo:'',
    id:'rtghyokr0g93',
    stringsNumber: StringsNumber.Seven,
    guitarType: GuitarType.Ukulele,
    vendorCode: '123456',
    price: 10000,
    createdAt: '2023-9-15',
  },
  {
    title: 'Guitar5',
    description: 'Not good guitar',
    photo:'',
    id:'rtgewfwefhiuiiij3',
    stringsNumber: StringsNumber.Seven,
    guitarType: GuitarType.Ukulele,
    vendorCode: '123456',
    price: 1000000,
    createdAt: '2023-9-15',
  },
  {
    title: 'Guitar6',
    description: 'Not good guitar',
    photo:'',
    id:'rtghyokeewvyyyeq3',
    stringsNumber: StringsNumber.Twelve,
    guitarType: GuitarType.Electro,
    vendorCode: '123456',
    price: 3300,
    createdAt: '2023-9-15',
  },
  {
    title: 'Guitar7',
    description: 'Not good guitar',
    photo:'',
    id:'rtghyoewf9k',
    stringsNumber: StringsNumber.Four,
    guitarType: GuitarType.Electro,
    vendorCode: '123456',
    price: 570,
    createdAt: '2023-9-15',
  },
  {
    title: 'Guitar8',
    description: 'Not good guitar',
    photo:'',
    id:'rtghyokk123',
    stringsNumber: StringsNumber.Six,
    guitarType: GuitarType.Acoustic,
    vendorCode: '123456',
    price: 6790,
    createdAt: '2023-9-15',
  },
];
